### ISSUE TITLE
ValueError: invalid literal for int() with base 10:''

### ISSUE THREAD

**Issue by absognety** [anelachan/sentimentanalysis#3]
having an issue with `SentiWordNet_3.0.0_20130122.txt` with `self.build_swn()`
after removing headers renamed the file to `SentiWordNet_new.txt`

`s = SentimentAnalysis('C:\\Users\\cvikas10\\Documents\\packages\\sentimentanalysis\\SentiWordNet_new.txt', weighting='geometric')`

```
Traceback (most recent call last):
 File "<ipython-input-16-819bacd27531>", line 2, in <module>
    weighting='geometric')
File "C:\Users\cvikas10\Documents\packages\sentimentanalysis\sentiment.py", line 24, in __init__
    self.build_swn(filename, weighting)
File "C:\Users\cvikas10\Documents\packages\sentimentanalysis\sentiment.py", line 61, in build_swn
    sense_num = int(word_num.split('#')[1])
ValueError: invalid literal for int() with base 10: ''

```

after debugged above error by saving UTF-8 had another issue
`s = SentimentAnalysis('C:\\Users\\cvikas10\\Documents\\packages\\sentimentanalysis\\SentiWordNet_new.txt',weighting='geometric')`

```
Traceback (most recent call last):
File "<ipython-input-17-819bacd27531>", line 2, in <module>
    weighting='geometric')
File "C:\Users\cvikas10\Documents\packages\sentimentanalysis\sentiment.py", line 24, in __init__
    self.build_swn(filename, weighting)
 File "C:\Users\cvikas10\Documents\packages\sentimentanalysis\sentiment.py", line 64, in build_swn
    if word not in self.swn_pos[pos]:
KeyError: 'ï»¿a'

```

**Comment by absognety** [comment]
Is it an issue with encoding UTF-8 or ASCII ? I am working in windows 10

**Comment by Lithen7** [comment]
At the end of 'SentiWordNet.txt', there is an extra #. Delete it and everything runs well.

**Comment by absognety** [comment]
deleted the # at the end of the file then faced with following traceback
```
Traceback (most recent call last):

  File "<ipython-input-363-02524c7fa0bc>", line 1, in <module>
    runfile('C:/Users/cvikas10/Documents/packages/sentimentanalysis/lexicon_recognizer.py', wdir='C:/Users/cvikas10/Documents/packages/sentimentanalysis')

  File "C:\AnacondaIDE\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\AnacondaIDE\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/cvikas10/Documents/packages/sentimentanalysis/lexicon_recognizer.py", line 2, in <module>
    s = SentimentAnalysis('C:\\Users\\cvikas10\\Documents\\packages\\sentimentanalysis\\SentiWordNet_3.0.0_20130122.txt', weighting='geometric')

  File "C:\Users\cvikas10\Documents\packages\sentimentanalysis\sentiment.py", line 24, in __init__
    self.build_swn(filename, weighting)

  File "C:\Users\cvikas10\Documents\packages\sentimentanalysis\sentiment.py", line 57, in build_swn
    words = rec[4].split()

IndexError: list index out of range
```
